### ISSUE TITLE
Rails 5.2.3 support

### ISSUE THREAD

**Issue by tchukuchuk** [rootstrap/active-storage-base64#29]
Hi,

I have this error when I try to add your gem :
`active_storage_base64 was resolved to 0.1.3, which depends on
      rails (~> 5.2.0, <= 5.2.2)`

Is it possible to have your gem working with Rails 5.2.3 ?

Regards.

**Comment by atstockland** [comment]
Or, Rails 6

**Comment by Ricoch** [comment]
Hello there,
That change was made a while ago by a member of the community, you can check it here:
https://github.com/rootstrap/active-storage-base64/pull/27

We still need to do a deployment with a new version of the gem with this change though
For more insights into why it is not supported now check: https://github.com/rootstrap/active-storage-base64/issues/26

**Comment by santib** [comment]
Hey @tchukuchuk @atstockland sorry for the long time, I just released `v0.1.4` of the gem that works with `rails ~> 5.2`
