### ISSUE TITLE
Doc - Improve OS standars

### ISSUE THREAD

**Issue by fedeagripa** [rootstrap/active-storage-base64#38]
Add topics

**Comment by fedeagripa** [comment]
@santib topics are missing in the repo main page, check  https://github.com/rootstrap/rails_api_base (the labels below code section)

**Comment by santib** [comment]
@fedeagripa I don't have access to do that, maybe @matiasmansilla1989 or @Ricoch can do it?

**Comment by Ricoch** [comment]
Unfortunately I don't have access to do that neither

**Comment by matiasmansilla1989** [comment]
@santib I granted you admin privileges of this repo since you have been maintaining it.
