### ISSUE TITLE
missing keywords: io, filename

### ISSUE THREAD

**Issue by matedemorphy** [rootstrap/active-storage-base64#46]
I just tried with a simple model and a simple configuration. I've allready run active storage migrations, it could be that?

**Comment by santib** [comment]
Hi @matedemorphy did you follow the `README`? If you did follow it, would you mind being more specific on the lines of code you added?

Having installed `ActiveStorage` and ran migrations is perfect, this gem is just an extension on top of it.

**Comment by matedemorphy** [comment]
@santib this is the code:

post model
```ruby
class Picking < ApplicationRecord
  include ActiveStorageSupport::SupportForBase64

  has_one_base64_attached  :image
end
```

post controller

```ruby
class Api::V1::PostsController < Api::V1::BaseController
  def create
    @post= Post.new(post_params)
    if @post.save
    	@post.image.attach(data: params[:post][:image])
    end
  end

  private
    def post_params
        params.require(:post).permit(:title, :body)
     end
end
```

postman post request
```javascript
{
  "post": {
       "title":"First Post",
	"body": "content for the post",
	"image": "/9j/4RNBRXhpZgAATU0AKg...."
	}
}

**Comment by santib** [comment]
@matedemorphy Great thanks for clarifying, I think your error is that the value of the `params[:post][:image]` should be in the [data uri format](https://github.com/rootstrap/active-storage-base64#data-format) instead of `"/9j/4RNBRXhpZgAATU0AKg...."` so you are missing a small part before the actual data.

**Comment by matedemorphy** [comment]
Thanks for the answer: @santib

new postman post request
```javascript
{
  "post": {
       "title":"First Post",
	"body": "content for the post",
	"image": "data:image/jpeg;base64,/9j/4RNBRXhpZgAATU0AKg...."
	}
}
```
Now i'm getting thi error: 
```
ActiveSupport::MessageVerifier::InvalidSignature in Api::V1::PickingsController#create
```

**Comment by santib** [comment]
@matedemorphy hmm just to discard a common issue, is the `Content-Type` header `application/json` ?

**Comment by matedemorphy** [comment]
if i use strong params, like this:
```ruby
  def create
    @post= Post.create(post_params)
  end

   def post_params
       params.require(:post).permit(:title, :body, :image)
    end
```

Then the error is this:

```
ActiveSupport::MessageVerifier::InvalidSignature in Api::V1::PickingsController#create
```
😭

**Comment by santib** [comment]
if you want to use strong params I think you need to do it this way 
```
    def post_params
       params.require(:post).permit(:title, :body, image: :data)
    end
```
notice the `data` is also whitelisted.

Did you check that your Content-Type sent in postman is fine?

**Comment by matedemorphy** [comment]
@santib 

In post headers:
Content-Type: application/json

**Comment by matedemorphy** [comment]
following your suggestion:
```ruby
 def post_params
   params.require(:post).permit(:title, :body, image: :data)
 end

I'm getting in the console: Unpermitted parameters: :image

I just realize this "error"? in console:  ```Can't verify CSRF token authenticity.```

it will have something to do?, I am trying to upload the image to Cloudinary, but I am sure that this configuration is correct

**Comment by santib** [comment]
oh yes seems like that could be the issue. https://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html , if you are using an API I don't think you can use the Rails CSRF protection

**Comment by matedemorphy** [comment]
Thanks for your help @santib 

Ok, i've changed

```ruby
protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
````
for:

```ruby
protect_from_forgery unless: -> { request.format.json? }
````

```
ActiveStorage::IntegrityError in Api::V1::PostsController#create
Unsupported source URL: #<StringIO:0x00007fdcdc7b05f0>
```

This is for a React Native app, i started following this [tutorial](https://medium.com/@ashley_foster/react-native-image-uploads-with-activestorage-ec4898317a82), but it didn't work out for me, so i intaled active-storage-base64 gem, to add support for base64 attachments to ActiveStorage, saddly I'm going for 2 days of being with this problem and I can't make it work 😩

**Comment by santib** [comment]
@matedemorphy Is it possible that those issues are related to cloudinary not to ActiveStorage itself?

**Comment by matedemorphy** [comment]
Thnaks for keep trying to help me @santib. cloudinary is ok. meanwhile don't try to uplosd using base64, wich is exactly what the app needs.

I've allready try this:
```
decoded_data = Base64.decode64(data)
washed_image = MiniMagick::Image.read(decoded_data)
washed_image.format("png")
object.images.attach(
io: StringIO.new(washed_image.to_blob),
filename: "image.png",
content_type: "image/jpeg"
)
```
😕

**Comment by santib** [comment]
@matedemorphy I think the error you are having is not because of this gem, but because of cloudinary + active storage. Why don't you try what they said in the comment in the issue I references before: `io: washed_image.to_blob` instead of `io: StringIO.new(washed_image.to_blob)` so like this

**Comment by matedemorphy** [comment]
@santib please could you show the complete code that you would implement

**Comment by santib** [comment]
I don't have the complete code because I don't even have the failing code, but from the issue in cloudinary I would try this
```
decoded_data = Base64.decode64(data)
washed_image = MiniMagick::Image.read(decoded_data)
washed_image.format("png")
object.images.attach(
  io: washed_image.to_blob,
  filename: "image.png",
  content_type: "image/jpeg"
)
```

**Comment by matedemorphy** [comment]
should i replace "object.images" for "post.image"?

**Comment by matedemorphy** [comment]
😤
undefined method `read' for #<String:0x00007f7b3400e720>

**Comment by gizipp** [comment]
https://github.com/cloudinary/cloudinary_gem/issues/366#issuecomment-600620959

> @matedemorphy I think the error you are having is not because of this gem, but because of cloudinary + active storage. Why don't you try what they said in the comment in the issue I references before: `io: washed_image.to_blob` instead of `io: StringIO.new(washed_image.to_blob)` so like this

Yeah, seems like it cloudinary gem issue
https://github.com/cloudinary/cloudinary_gem/issues/366#issuecomment-600620959

**Comment by haroldofurtado** [comment]
Having here almost the same problem.

`def farmer_params
        ActiveModelSerializers::Deserialization.jsonapi_parse(params)
end`

**Comment by haroldofurtado** [comment]
Got the solution:

Just changed:
`"picture": {"data": "base64"}`
