### ISSUE TITLE
Transforming Images

### ISSUE THREAD

**Issue by mhmdAljefri** [rootstrap/active-storage-base64#47]
I want to enable variants, like Rails Active Storage. [Transforming Images Guide](https://edgeguides.rubyonrails.org/active_storage_overview.html#transforming-images)

I tried to add the processing image gem `image_processing`, then use variant method:

```
Model.avatar.variant(resize_to_limit: [100, 100])
```

**expected behavior:**

resized image 

**Current behavior:**

```
rescue in method_missing
Caused by NoMethodError: undefined method 'variant' for #<ActiveStorageSupport::Base64One:0x0000000002d22510>
```

Any help to implement this with ability of use base64 files

**Comment by santib** [comment]
It is working for me
![image](https://user-images.githubusercontent.com/6373536/71590179-407db600-2b06-11ea-87cd-557819d6ac4d.png)

Versions:
ruby 2.6.5
rails 6.0.1
active_storage_base64 1.0.0

would you mind providing your versions?

**Comment by mhmdAljefri** [comment]
Versions:

`ruby 2.6.0p0
rails (5.2.3)
active_storage_base64 (0.1.4)`

**Comment by santib** [comment]
@mhmdAljefri Seems like it wasn't a problem with the versions. I was able to reproduce it by calling `variant` to an empty attachment.

I don't think this is a bug introduced by the gem, I see the same error with `has_one_attached`.
Example:
```
class User
  has_one_base64_attached :avatar
  has_one_attached :image
end
```

![image](https://user-images.githubusercontent.com/6373536/71596352-fa345100-2b1d-11ea-8f67-d90ad50c4dd4.png)

So I think you'll solve this issue by doing `Model.avatar.variant(resize_to_limit: [100, 100]) if Model.avatar.attached?`
