### ISSUE TITLE
uninitialized constant ApplicationRecord(abstract)::ActiveStorageSupport

### ISSUE THREAD

**Issue by ceo-ooo-ooo** [rootstrap/active-storage-base64#55]
/app/models/application_record.rb:3:in `<class:ApplicationRecord>': uninitialized constant ApplicationRecord(abstract)::ActiveStorageSupport (NameError)

pls help <3

Put the gem made the settings as indicated in the readme well he swears magic I don't think

```rb
class ApplicationRecord < ActiveRecord::Base
  include ActiveStorageSupport::SupportForBase64
  self.abstract_class = true
end
```

```rb
class User < ApplicationRecord
  has_one_base64_attached :avatar
end
```

**Comment by Ricoch** [comment]
Hey @ceo-ooo-ooo ,
I think we might need some more info here. What version of rails are you using? What version of the gem are you using? Can you paste your gemfile and gemfile.lock here?

**Comment by Ricoch** [comment]
@ceo-ooo-ooo 
I created a new repo with `rails new 'name'` command and added your Gemfile to it. It all seemed to work perfectly. Can you try to download this repo and run it to see if it works?
https://github.com/Ricoch/Issue55Example

**Comment by santib** [comment]
@ceo-ooo-ooo were you able to reproduce the bug in the sample repo that Ricoch provided? If not, did you find any difference with your repo where it was not working?

**Comment by ceo-ooo-ooo** [comment]
@Ricoch @santib 
I tried without docker everything was successful, but if everything is wrapped in docker everything is sad so far.
I will figure out why it doesn't work so easily with docker
thx

**Comment by ceo-ooo-ooo** [comment]
the problem for docker was BOOTSNAP!!!
