### ISSUE TITLE
Question: sending JSON to API

### ISSUE THREAD

**Issue by huylv** [rootstrap/active-storage-base64#72]
Hi,

My code looks like this:

Model:
```ruby
class Image < ApplicationRecord
  has_one_base64_attached :image_file
end
```

Controller:
```ruby
class ImagesController < ApplicationController
  def create
    @image = Image.new(image_params)

    if @image.save
      render json: @image, status: :created, location: @image
    else
      render json: @image.errors, status: :unprocessable_entity
    end
  end

  def image_params
    params.require(:image).permit(image_file: :data)
  end
```

Now I want to send a JSON to the API, I've tried different ways, none seems to work properly. What should it look like?
Thank you.

**Comment by sebastiancaraballo** [comment]
Hello @huylv, does this work?

```
{
  "image": {
    "data": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII"
  }
}
```

**Comment by huylv** [comment]
Hi @sebastiancaraballo,

With that payload, there is a server error `Unpermitted parameter: :data`
Looks like there is an image being created, too:

```
  TRANSACTION (0.4ms)  begin transaction
  ↳ app/controllers/api/latest/images_controller.rb:22:in `create'
  Image Create (0.6ms)  INSERT INTO "images" ("image_file", "created_at", "updated_at") VALUES (?, ?, ?)  [["image_file", nil], ["created_at", "2023-02-27 18:16:53.682491"], ["updated_at", "2023-02-27 18:16:53.682491"]]
  ↳ app/controllers/api/latest/images_controller.rb:22:in `create'
  TRANSACTION (1.8ms)  commit transaction
```
but the `image_file` is `nil`.

**Comment by sebastiancaraballo** [comment]
@huylv My bad, please try:
```
{
  "image": {
    "image_file": {
      "data": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII"
    }
  }
}
```

**Comment by sebastiancaraballo** [comment]
@huylv I don't think that should be necessary. Can you provide me more context about `image_url`?
Another way to check if the image is actually attached using `rails console`:
`Image.last.image_file.attached?`

**Comment by huylv** [comment]
Hi @sebastiancaraballo,

I just uploaded the whole source code [here](https://github.com/huylv/rails-api-noob). It's super simple, there are only several files. The `image_url` as far as I understand comes from the part `location: @image` in the controller (see the code I posted above).

```
irb(main):001:0> Image.last.image_file.attached?
  Image Load (0.5ms)  SELECT "images".* FROM "images" ORDER BY "images"."id" DESC LIMIT ?  [["LIMIT", 1]]
  ActiveStorage::Attachment Load (0.7ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = ? AND "active_storage_attachments"."record_type" = ? AND "active_storage_attachments"."name" = ? LIMIT ?  [["record_id", 46], ["record_type", "Image"], ["name", "image_file"], ["LIMIT", 1]]
=> true
```

I just started learning Rails from some Youtube tutorials so everything is new to me 😊

**Comment by sebastiancaraballo** [comment]
@huylv Great, that's a good start. I see the image is attached now so I'm closing this issue. I recommend using a gem like [jbuilder](https://github.com/rails/jbuilder) or similar to declare views and specify the attributes to return.

**Comment by huylv** [comment]
@sebastiancaraballo: Thank you for your help. Is the image already stored as an image rather than a base64 string?
